# Generated by Django 3.2.12 on 2022-04-02 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttocourse',
            name='note',
        ),
        migrations.AddField(
            model_name='studenttocourse',
            name='difficulty',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Difficulty'),
        ),
        migrations.AddField(
            model_name='studenttocourse',
            name='grade',
            field=models.PositiveIntegerField(default=0, verbose_name='Grade'),
        ),
    ]
