# Generated by Django 3.2.12 on 2022-04-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220402_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttocourse',
            old_name='participation_to_the_course',
            new_name='attended',
        ),
    ]
