# Generated by Django 3.2.12 on 2022-04-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloc_type', models.CharField(choices=[('study', 'Étude'), ('pause', 'Pause')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('ects', models.PositiveIntegerField(default=0, verbose_name='ECTS')),
                ('course_color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_time_per_day', models.TimeField(default='08:00:00', verbose_name="Temps d'étude par jour")),
                ('study_days_per_week', models.PositiveIntegerField(default=7, verbose_name="Jours d'étude par semaine")),
                ('study_bloc_size', models.TimeField(default='08:00:00', verbose_name="Taille d'un bloc d'étude")),
                ('starting_hour', models.TimeField(default='08:00:00')),
                ('ending_hour', models.TimeField(default='18:00:00')),
                ('pause_duration', models.TimeField(default='00:30:00', verbose_name='Durée de la pause')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Planning de ouf fréro', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='date')),
                ('start_hour', models.TimeField(default='08:00:00')),
                ('end_hour', models.TimeField(default='09:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('website', models.CharField(default='example.com', max_length=100)),
            ],
        ),
    ]
