# Generated by Django 3.2.12 on 2022-04-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ects',
            field=models.PositiveIntegerField(default=0, verbose_name='ECTS'),
        ),
    ]
