# Generated by Django 3.2.12 on 2022-04-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='Planning de ouf fréro', max_length=200),
        ),
    ]
