# Generated by Django 3.2.12 on 2022-04-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_block_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_color',
        ),
        migrations.AddField(
            model_name='course',
            name='course_class',
            field=models.CharField(choices=[('course_1', 'course_1'), ('course_2', 'course_2'), ('course_3', 'course_3'), ('course_4', 'course_4'), ('course_5', 'course_5')], default='course_1', max_length=8),
        ),
    ]
