# Generated by Django 3.2.12 on 2022-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_timetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='ending_hour',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='study_bloc_size',
            field=models.PositiveIntegerField(default=2, verbose_name="Taille d'un bloc d'étude"),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='study_days_per_week',
            field=models.PositiveIntegerField(default=7, verbose_name="Jours d'étude par semaine"),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='study_time_per_day',
            field=models.PositiveIntegerField(default=8, verbose_name="Temps d'étude par jour"),
        ),
    ]
