# Generated by Django 3.2.12 on 2022-04-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20220402_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='study_bloc_size',
            field=models.TimeField(default='08:00:00', verbose_name="Taille d'un bloc d'étude"),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='study_time_per_day',
            field=models.TimeField(default='08:00:00', verbose_name="Temps d'étude par jour"),
        ),
    ]
